import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# AI Model Performance for Individual Movies
# Grouped Bar Chart

merged_df = pd.read_csv('../cosine_similarity_and_other_tests/cosine_similarity_results_subtitles_by_movie.csv')

merged_df["File"] = merged_df["File"].replace({
    "aireviews_chatgpt.csv": "ChatGPT",
    "aireviews_deepseek.csv": "DeepSeek",
    "aireviews_gemini.csv": "Gemini",
    "aireviews_gemini_context_variation.csv": "Gemini (Context)"
})

merged_df.rename(columns={'File': 'AI Model'}, inplace=True)

movie_info_df = pd.read_csv('../selected_movie_info.csv')

# Merge the AI model dataframe with the movie info dataframe on 'MovieID' and 'imdb_id'
merged_df = merged_df.merge(movie_info_df[['imdb_id', 'movie']], left_on='MovieID', right_on='imdb_id', how='left')

# Drop the 'imdb_id' column and rename 'movie' to 'MovieName'
merged_df.drop(columns=['imdb_id','MovieID'], inplace=True)

# Display the result
# print(merged_df.head())

# Plot
plt.figure(figsize=(12, 8))
sns.barplot(data=merged_df, x="movie", y="MeanSimilarity", hue="AI Model",  palette="Set2")

# Labels and title
plt.xlabel("Movie")
plt.ylabel("Mean Cosine Similarity")
plt.title("Cosine Similarity Between IMDb and AI Reviews (By Movie)")
plt.xticks(rotation=45,ha='right')
plt.legend(title="AI Model",fontsize=8)

plt.tight_layout()
plt.show()
# save fig
plt.savefig("similarity_comparison_by movie(subtitles).png", dpi=300, bbox_inches="tight")

# The plot measures how well AI-generated reviews resemble human-written IMDb reviews using cosine rimilairty across movies

# Observations:
# 1. DeepSeek generally shows the highest similarity  across movies
# This sugggests that DeepSeek generates reviews are most similar to IMDb reviews in terms of word choice and word frequency

# 2.ChatGPT consistently has the lowest cosine similarity
# This implies that reviews generated by ChatGPT differ the most from IMDb reviews;
# It might becasue ChatGPT use more diverse vocabulary or vary in phrase compared to human-written reviews.
# Also, this could because ChatGPT generate more descriptive or creative responses rather than mimicking human writting pattern.

# 3. Both Gemini models consistently have moderate cosine similarity scores, lower than DeepSeek's scores, but higher than ChatGPT's, for all movies.
# This may becuase Gemini model is trained to balance creativity and accuracy, rather than being highly
# Both Gemini models (simple and detailed prompts) have closely similarity scores across all movies
# This indicates that providing additonal context does not significantly change Gemini's ability to match human reviews
# This may because Gemini's review-generation method is already well-tuned, and additional context does not drastically alter its writting style.
# Questions we may interest: When we providing detailed prompts to other AI models, will they perform as well as we proving simple prompts?

# 4. Performance by movies
# From the bar plot, some movies show slightly differences between models, while other have more consistent performance
# For example,
# 1. the third group of bars, representing 'The Shawshank Redemption',appears more balanced,
#  meaning the cosine similarity are closer together than other movies.
# Possible reasons for balanced performance:
# Highly positive reviews are easier for AI to mimic:
# 'The Shawshank Redemption' has the highest average positive polarity scores and the seconf lowest average polarity scores
# for IMDb reviews with ratings above 7.
# If IMDb reviews for 'The Shawshank Redemption' are generally positive, the language used in those reviews is likely more stndarised, and repetitive
# (trigram analysis: from all_imdb_reviews_trigrams.csv, the third most common trigram (three-word phrase) is 'best film time', this is a strong indication)

# How to expalin balanced AI performance: ?
#

# 2. the fourth group of bars, representing 'Nomadland', ChatGPT similairty scores is significantly lower compared to other AI models.
# And other AI models(Gemini and DeepSeek) have relatively balanced performance
# Possible reasons for this:
# ChatGPT emotion recognition: ChatGOT might generate more generic or analytic reviews, failing to capture the emotional depth of human reviews.

# 3. The sixth group of bars, representing 'Titanic', DeepSeek similarity score is noticeably higher
# Possible reason for this:
# DeepSeek have better ability to interpret the narratives. The trigram 'Tragic True Story' suggests that DeepSeek is likely
# capturing the narrative nature of text.
# DeepSeek might be more tuned to handle complex emotional narratives.
#

# Further Analysis:
# trigram frequence vs. cosine similarity ?


